### ISSUE TITLE
Use base64 to try to void having reflected content on the HTML (youtube question)

### ISSUE THREAD

**Issue by rafaelrpinto** [dionyziz/rupture#217]
Hi!

I'm sorry if this is not the correct place to ask questions.

I kinda asked this question on youtube (https://www.youtube.com/watch?v=T4iTwNLPv4g), but thats  not a very good place to have a discussion, so if you don't mind I will ask it here. 

Imagine my site has a search page and when no items are found I display : `No results found for 'Rafael' `.  I imagine this is one of many types of reflected content that allow you to bootstrap a compression attack.

But now imagine that instead of returning the search term in the HTML I create a little framework that works somehow like `No results found for '<span class='base64Content'>UmFmYWVs</span>' ` where on the client side I get all elements of the class `base64Content` and convert it to plaintext before the page loads.

It would still look like `No results found for 'Rafael'` once the page loads, but the returned HTML won't have the reflected content.

So there comes the question:

How could the attacker apply base64 to the guesses and still match the reflected content?

Because if they subit `UmFmYWVs` as search term to try to match the base64 representation of `Rafael`, the resulting HTML would be `No results found for '<span class='base64Content'>VW1GbVlXVnM=</span>' ` and so on for each guess.

Sorry again if it's a silly question or if this is not the right place.

Thanks!

Rafael

**Comment by dimkarakostas** [comment]
Hello @rafaelrpinto . 

Your proposal is interesting, although there are some problems with it. 

Firstly, for some secrets the attacker may simply reverse the base64 encoding and submit a reflection that, when base64 encoded, matches the part of the secret he/she knows. In that case, the HTML will contain the base64 encoded reflection which will match your secret, so the attack will run as normal. For example, if the secret is "UmFmYWVs", e.g. a CSRF token, and the attacker submits "Raf" and "Rag", the base64 encoded reflections will be "UmFm" and "UmFn", so the first will match the secret. You should assume that the attacker knows a prefix of the secret, as well as the fact that you use base64.

Secondly, using base64 practically makes the secret uncompressible, since the base64 encoded value will not match any other part of the page. This has been proposed before, by either using annotation to disable compression for certain (or all) parts of the page or masking secrets [like Facebook does](https://www.facebook.com/notes/protect-the-graph/preventing-a-breach-attack/1455331811373632).

Cheers,
Dimitris.

**Comment by dionyziz** [comment]
Rafael – this is in principle a good idea, but as Dimitris pointed out, it fails as the attacker can still attack. Next week in Black Hat Europe in London, we'll talk about how to create a better scheme that allows a proper defence, and we'll launch an open source framework that will allow you to do it. Keep an eye out ;)

**Comment by rafaelrpinto** [comment]
@dimkarakostas
Thanks for the response.
Now I see your point, base64 wouldn't really solve it.

@dionyziz 
Cool. I will check it out!

Thanks guys!
Rafael

**Comment by rafaelrpinto** [comment]
Sorry! One more question, please :)

And if the secret has random characters outside base64 alphabet, like '-' and '_'?

```html
<input type="hidden id"_csrf"" value="_AB-CD_12-ZZ_00"/>
```
In theory the attacker wouldn't be able to reflect this though base64, right?

**Comment by dionyziz** [comment]
The problem is you can't always know what the reflection is. For example, the attacker may be using the search query string as a reflection variable like you mentioned, but they could also use something else. The "reflection" doesn't have to be an actual reflection; it could be a stored attack, similar to stored XSS.

For the example of let's say Gmail, the attacker could put the "reflected" variable in the e-mail subject, then shoot an e-mail to the victim. When the victim issues an HTTPS request to the page, the "reflection" (attacker-chosen email subject, not base64-encoded) is then rendered together with the secret, making the attack possible again.

**Comment by dionyziz** [comment]
See also my blog post [unexpected secrets and reflections](https://www.ruptureit.com/blog/2016/07/27/unexpected-secrets-and-reflections/).

**Comment by rafaelrpinto** [comment]
@dionyziz
Thank you for taking the time to answer me.
You are right, chase reflected content is a lost battle.
I will wait for your next presentation!
Cheers,
Rafael
